project:
  type: website
  output-dir: ../../docs/statcomputing

execute:
  kernel: python3
  
website:
  site-url: https://honglang.github.io/statcomputing/
  sidebar:
    style: docked
    title: "{{< var department-abbrev >}} {{< var number >}}"
    logo: assets/stat_bear.png
    logo-alt: "UC Berkeley Statistics logo"
    tools:
      - icon: github
        href: https://honglang.github.io/statcomputing/
        aria-label: GitHub
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: staff.qmd
        text: Staff
      # - href: calendar.qmd
      #   text: Calendar
      - section: "Units"
        contents:
          - units/unit1.qmd
          - units/unit2.ipynb
          - units/unit3.qmd
      - href: data.qmd
        text: Datasets

          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html
